### ISSUE TITLE
support for shared hosting

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/beam#1]
currently this is not using travis for packaging, hence `composer install` needs to be run on the instance or locally (probably too complicated for most).  

moving this to travis would likely unlock a lot of users opt-in to the alpha.

**Comment by pjaudiomv** [comment]
done PR #3 closes this.

**Comment by pjaudiomv** [comment]
builds show up here https://archives.bmlt.app/index.html#beam/ and upon tag will release to github

**Comment by radius314** [comment]
the package worked well.
