### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/beam#4]
I followed the directions on installing and am getting the following error

`Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /home/charl767/beam/bootstrap/app.php:16 Stack trace: #0 /home/charl767/beam/public/index.php(38): require_once() #1 {main} thrown in /home/charl767/beam/bootstrap/app.php on line 16`

**Comment by radius314** [comment]
are you pointing your application folder to `/public`?

**Comment by radius314** [comment]
are you on shared hosting?

**Comment by pjaudiomv** [comment]
I am on shared hosting and im pointing the domain to the public folder

**Comment by radius314** [comment]
did the migrations run successfully?

**Comment by pjaudiomv** [comment]
BMLT_ROOT_SERVER=https://www.nerna.org/main_server          # Your root server address, for example: https://example.org/main_server

APP_ENV=production         # This does not need to change
APP_KEY=K+lD8BBoecY3/QKEY_HERE_/RM=                   # Visit this site https://generate.plus/en/base64 (ensure the bit length is set to 32) and generate a random $
APP_DEBUG=false            # Used for additional debugging, leaving as
false for production
APP_URL=http://localhost   # This does not need to change

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost          # Set to the host of your database server, if on the same instance put as localhost
DB_PORT=3306               # The MySQL database port, default is 3306
DB_DATABASE=db_beam  # The name of the database
DB_USERNAME=db_beam  # The database username
DB_PASSWORD=dbpassword    # The database password

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com            # The SMTP mail server hostname
MAIL_PORT=587            # The SMTP mail server port
MAIL_USERNAME=email@gmail.com        # The SMTP mail username
MAIL_PASSWORD=pass        # The SMTP mail password
MAIL_ENCRYPTION=true
MAIL_FROM_ADDRESS=email@gmail.com    # The SMTP mail from address
MAIL_FROM_NAME=Beam       # The SMTP mail from name

**Comment by pjaudiomv** [comment]
no they did not I get that same error

**Comment by radius314** [comment]
Any additional info in the log file? `storage/logs`

**Comment by pjaudiomv** [comment]
no log file in the logs folder

**Comment by radius314** [comment]
is the vendor folder present?  does the user that the webserver users have permissions?

**Comment by pjaudiomv** [comment]
yea the vendor folder is there and same owner/group as rest of server

**Comment by radius314** [comment]
resolved by https://github.com/bmlt-enabled/beam/pull/5
